apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: default

resources:
  - ml-service.yaml
  - stub-services.yaml

commonLabels:
  app.kubernetes.io/part-of: recommendation-engine

images:
  - name: ml-service
    newTag: test
  - name: api-gateway
    newTag: test
  - name: cache-service
    newTag: test
  - name: stream-processor
    newTag: test
  - name: user-service
    newTag: test