apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: verticalpodautoscalers.autoscaling.k8s.io
  labels:
    app.kubernetes.io/name: vertical-pod-autoscaler
    app.kubernetes.io/version: "1.0.0"
spec:
  group: autoscaling.k8s.io
  versions:
  - name: v1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  apiVersion:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
                required:
                - apiVersion
                - kind
                - name
              updatePolicy:
                type: object
                properties:
                  updateMode:
                    type: string
                    enum: ["Off", "Initial", "Recreate", "Auto"]
                    default: "Auto"
              resourcePolicy:
                type: object
                properties:
                  containerPolicies:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        mode:
                          type: string
                          enum: ["Auto", "Off"]
                        minAllowed:
                          type: object
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                        maxAllowed:
                          type: object
                          additionalProperties:
                            anyOf:
                            - type: integer
                            - type: string
                        controlledResources:
                          type: array
                          items:
                            type: string
                            enum: ["cpu", "memory"]
            required:
            - targetRef
          status:
            type: object
            properties:
              conditions:
                type: array
                items:
                  type: object
                  properties:
                    type:
                      type: string
                    status:
                      type: string
                    lastTransitionTime:
                      type: string
                      format: date-time
                    reason:
                      type: string
                    message:
                      type: string
              recommendation:
                type: object
                properties:
                  containerRecommendations:
                    type: array
                    items:
                      type: object
                      properties:
                        containerName:
                          type: string
                        target:
                          type: object
                          additionalProperties:
                            type: string
                            pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
                        lowerBound:
                          type: object
                          additionalProperties:
                            type: string
                            pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
                        upperBound:
                          type: object
                          additionalProperties:
                            type: string
                            pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
                        uncappedTarget:
                          type: object
                          additionalProperties:
                            type: string
                            pattern: '^(\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))(([KMGTPE]i)|[numkMGTPE]|([eE](\+|-)?(([0-9]+(\.[0-9]*)?)|(\.[0-9]+))))?
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa
  scope: Namespaced
  names:
    plural: verticalpodautoscalers
    singular: verticalpodautoscaler
    kind: VerticalPodAutoscaler
    shortNames:
    - vpa