name: Kubernetes Tests

on:
  workflow_dispatch:
  push:
    paths:
      - 'k8s/**'
      - 'services/*/Dockerfile'
      - '.github/workflows/k8s-test.yml'
  pull_request:
    paths:
      - 'k8s/**'
      - 'services/*/Dockerfile'

jobs:
  k8s-integration:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Create Kind config file
        run: |
          mkdir -p /tmp
          cat <<EOF > /tmp/kind-config.yaml
          kind: Cluster
          apiVersion: kind.x-k8s.io/v1alpha4
          nodes:
            - role: control-plane
            - role: worker
          EOF
      
      - name: Create Kind cluster
        uses: helm/kind-action@v1.10.0
        with:
          version: v0.22.0
          config: /tmp/kind-config.yaml
          cluster_name: test-cluster
          wait: 300s
      
      - name: Verify cluster is ready
        run: |
          kubectl version --client
          kubectl cluster-info
          kubectl get nodes
          kubectl wait --for=condition=Ready nodes --all --timeout=60s
      
      # Step 1: Install CRDs first (if they exist)
      - name: Install CRDs
        run: |
          if [ -f "k8s/crds/vpa-v1-crd.yaml" ]; then
            echo "Installing VPA CRD..."
            kubectl apply -f k8s/crds/vpa-v1-crd.yaml
            kubectl wait --for condition=established --timeout=60s crd/verticalpodautoscalers.autoscaling.k8s.io
          else
            echo "No VPA CRD found, skipping..."
          fi
      
      # Step 2: Build and load only existing services
      - name: Build and load Docker images
        run: |
          SERVICES="user-service ml-service stream-processor cache-service api-gateway"
          for service in $SERVICES; do
            if [ -d "services/$service" ] && [ -f "services/$service/Dockerfile" ]; then
              echo "Building $service..."
              if docker build -t $service:test services/$service/; then
                echo "Loading $service image to Kind..."
                kind load docker-image $service:test --name test-cluster
                echo "✅ $service ready"
              else
                echo "⚠️  $service build failed, skipping..."
              fi
            else
              echo "⚠️  $service directory/Dockerfile not found, skipping..."
            fi
          done
    
      # Step 3: Create namespace
      - name: Create namespace
        run: |
          kubectl create namespace recommendation-system --dry-run=client -o yaml | kubectl apply -f -
          kubectl create namespace monitoring --dry-run=client -o yaml | kubectl apply -f - || true

      # Step 4: Apply secrets first (if they exist)
      - name: Apply secrets
        run: |
          if [ -f "k8s/base/secrets.yaml" ]; then
            echo "Applying secrets..."
            kubectl apply -f k8s/base/secrets.yaml -n recommendation-system
          else
            echo "No secrets file found, creating dummy secret..."
            kubectl create secret generic app-secrets \
              --from-literal=redis-password=dummy \
              --from-literal=db-password=dummy \
              -n recommendation-system \
              --dry-run=client -o yaml | kubectl apply -f -
          fi
          
      # Step 5: Apply base services
      - name: Deploy base services
        run: |
          if [ -d "k8s/base" ] && [ -f "k8s/base/kustomization.yaml" ]; then
            echo "Deploying with Kustomize..."
            kubectl apply -k k8s/base
          elif [ -d "k8s/base" ]; then
            echo "Applying base YAML files..."
            kubectl apply -f k8s/base/ -n recommendation-system || true
          else
            echo "No base services found, skipping..."
          fi
      
      # Step 6: Wait for deployments to be ready
      - name: Wait for deployments
        run: |
          echo "Waiting for deployments to be ready..."
          kubectl wait --for=condition=available --timeout=180s deployment --all -n recommendation-system || {
            echo "Some deployments failed to start, checking status..."
            kubectl get pods -n recommendation-system
            kubectl get events -n recommendation-system --sort-by='.lastTimestamp' | tail -10
          }
      
      # Step 7: Apply monitoring (optional)
      - name: Deploy monitoring
        run: |
          if [ -d "k8s/monitoring" ]; then
            echo "Deploying monitoring stack..."
            kubectl apply -k k8s/monitoring -n monitoring || {
              echo "Monitoring deployment failed, continuing..."
              kubectl get events -n monitoring --sort-by='.lastTimestamp' | tail -5
            }
          else
            echo "No monitoring configuration found, skipping..."
          fi
      
      # Step 8: Basic smoke test
      - name: Run smoke tests
        run: |
          echo "Running basic connectivity tests..."
          kubectl run test-pod --image=busybox:1.36 --restart=Never --rm -i --timeout=30s \
            -- sh -c 'echo "Cluster is working"; sleep 5' || true
          
          echo "Checking service endpoints..."
          kubectl get svc -A
          kubectl get pods -A
      
      # Step 9: Debug on failure
      - name: Debug information
        if: failure()
        run: |
          echo "=== CLUSTER DEBUG INFO ==="
          kubectl get nodes
          kubectl get pods -A
          kubectl get svc -A
          kubectl get events -A --sort-by='.lastTimestamp' | tail -20
          echo "=== CRD Status ==="
          kubectl get crd | grep -i vpa || echo "No VPA CRDs found"
      
      # Step 10: Cleanup
      - name: Cleanup
        if: always()
        run: |
          echo "Cleaning up Kind cluster..."
          kind delete cluster --name test-cluster || true